---
galaxy_info:
  author: Carlos Camacho
  description: A simple killpods action for Pystol.
  company: Pystol
  license: Apache-2.0
  min_ansible_version: 1.2
  platforms:
    - name: Fedora
      versions:
        - 25
  galaxy_tags: ["pystol", "killpods"]
dependencies: []
